server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_categorie?createDatabaseIfNotExist=true&&useSSL=false&serverTimezone=UTC
    username: root
    password: admin

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  application:
    name: service-categorie

eureka:
  instance:
    hostname: localhost


  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
